apiVersion: v1
kind: Pod
metadata:
  name: kafkacat
  namespace: kafka
spec:
  containers:
  - name: kafka
    image: ubuntu:latest
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
